scanner:
  diff_only: True
  linter: pycodestyle
pycodestyle:
  max-line-length: 120
  ignore:
    - E402 # module level import not at top of file
    - C406 # Unnecessary list literal - rewrite as a dict literal.
