files:
  - source: /src/lang/zh_hans/*.yaml
    translation: /src/lang/%locale_with_underscore%/%original_file_name%
  - source: /README.md
    translation: '%original_path%/README_%locale_with_underscore%.md'
