[project]
name = "Moonlark"
version = "0.1.0"
description = "A new ChatBot"
readme = "README.md"
requires-python = ">=3.10, <4.0"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    { name = "OneBot V12", module_name = "nonebot.adapters.onebot.v12" }
]
plugins = [
    "nonebot_plugin_orm",
    "nonebot_plugin_alconna",
    "nonebot_plugin_htmlrender",
    "nonebot_plugin_saa"
]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.poetry]
name = "moonlark"
version = "0.1.0"
description = "A new ChatBot"
authors = ["XiaoDeng3386 <1744793737@qq.com>"]
license = "AGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nonebot2 = {extras = ["fastapi"], version = "^2.2.1"}
nonebot-adapter-onebot = "^2.4.3"
aiofiles = "^23.2.1"
nonebot-plugin-orm = {extras = ["default"], version = "^0.7.1"}
nonebot-plugin-alconna = "^0.41.1"
nonebot-plugin-htmlrender = "^0.3.1"
nonebot-plugin-send-anything-anywhere = "^0.6.0"

[tool.poetry.group.dev.dependencies]
nb-cli = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
