name: Check for 'from plugins' imports and comment on PR

on:
  pull_request:
    types: [opened, reopened, synchronize, closed, edited]

jobs:
  check-imports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check for 'from plugins' imports
      id: check-imports
      run: |
        echo "Checking for 'from plugins' imports..."
        result=$(grep -rl '^from plugins' --include='*.py' || echo "")
        echo "Found files with 'from plugins' imports:"
        echo "$result"
        echo "::set-output name=files::$result"
        lines=$(grep -rn '^from plugins' --include='*.py' | wc -l)
        echo "::set-output name=lines::$lines"
        echo "Counting lines..."
        echo "$lines lines found."

    - name: Comment on PR with line count
      if: steps.check-imports.outputs.files != ''
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const files = `${{ steps.check-imports.outputs.files }}`;
          const lines = `${{ steps.check-imports.outputs.lines }}`;
          const message = `Found 'from plugins' imports in ${lines} lines across the following files:\n${files}`;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

    - name: Set failure if imports found
      if: steps.check-imports.outputs.files != ''
      run: |
        echo "Failing the job due to 'from plugins' imports"
        exit 1